export const RESTAURANT = {
  name: "Elitte Bella Italia",
  tagline: "Autentična italijanska kafa i pizza u srcu Kotor Varoša",
  phone: "+387 51 924-000",
  phoneHref: "tel:+38751924000",
  address: "Cara Dušana 62, Kotor Varoš 78220",
  country: "Bosna i Hercegovina",
  instagram: "https://www.instagram.com/elitte_bella_italia/",
  hours: "Svaki dan 07:00 – 23:00",
  mapEmbed:
    "https://maps.google.com/maps?q=Cara%20Du%C5%A1ana%2062%2C%20Kotor%20Varo%C5%A1%2078220&t=&z=16&ie=UTF8&iwloc=&output=embed",
  mapLink:
    "https://www.google.com/maps/search/?api=1&query=Cara+Du%C5%A1ana+62,+Kotor+Varo%C5%A1+78220",
} as const;

export const GALLERY = [
  { src: "/galerija/galerija-01.png", alt: "Pizza Elitte Bella Italia" },
  { src: "/galerija/galerija-02.png", alt: "Pizza iz peći" },
  { src: "/galerija/galerija-03.png", alt: "Specijalitet pizzerije" },
  { src: "/galerija/galerija-04.png", alt: "Svježa pizza" },
  { src: "/galerija/galerija-05.png", alt: "Italijanska pizza" },
  { src: "/galerija/galerija-06.png", alt: "Pizza s preljevom" },
  { src: "/galerija/galerija-07.png", alt: "Ambijent restorana" },
  { src: "/galerija/galerija-08.png", alt: "Pizza za stolom" },
  { src: "/galerija/galerija-09.png", alt: "Desert" },
  { src: "/galerija/galerija-10.png", alt: "Jelo iz menija" },
  { src: "/galerija/galerija-11.png", alt: "Specijalitet kuće" },
  { src: "/galerija/galerija-12.png", alt: "Pizza Capricciosa" },
  { src: "/galerija/galerija-13.png", alt: "Doručak" },
  { src: "/galerija/galerija-14.png", alt: "Mješovita pizza" },
  { src: "/galerija/galerija-15.png", alt: "Pepperoni pizza" },
  { src: "/galerija/galerija-16.png", alt: "Terasa" },
  { src: "/galerija/galerija-17.png", alt: "Pizza Quattro Stagioni" },
  { src: "/galerija/galerija-18.png", alt: "Margherita" },
  { src: "/galerija/galerija-19.png", alt: "Vegetarijanska pizza" },
  { src: "/galerija/galerija-20.png", alt: "Pizza s morskim plodovima" },
  { src: "/galerija/galerija-21.png", alt: "Pizza s cherry paradajzom" },
  { src: "/galerija/galerija-22.png", alt: "Pizza s pršutom" },
  { src: "/galerija/galerija-23.png", alt: "Pizza Tricolore" },
  { src: "/galerija/galerija-24.png", alt: "Pizza s pršutom i sirom" },
  { src: "/galerija/galerija-25.png", alt: "Pizza s jajima" },
  { src: "/galerija/galerija-26.png", alt: "Kafa Elitte Bella Italia" },
  { src: "/galerija/galerija-27.png", alt: "Ukusna pizza" },
  { src: "/galerija/galerija-28.png", alt: "Klasična pizza" },
  { src: "/galerija/galerija-29.png", alt: "Specijalna pizza" },
] as const;
